name: new_project
description: ''
creation_date: 2024/08/25 16:54
pykasso_version: 0.1.3
grid:
  x0: 0
  y0: 0
  z0: 0
  nx: 10
  ny: 10
  nz: 10
  dx: 10
  dy: 10
  dz: 10
core:
  locations:
    root: c:\Users\franc\OneDrive\Desktop\pykasso\pykasso\notebooks\geometry
    project: c:\Users\franc\OneDrive\Desktop\pykasso\pykasso\notebooks\geometry/new_project/
  paths:
    project_dir: new_project/
    inputs_dir: new_project/inputs/
    outputs_dir: new_project/outputs/
  filenames:
    parameters: parameters.yaml
    project: project.yaml
    log: project.log
n_simulations: 0
simulations: []
